Presentation

diff --git a/minix/drivers/storage/ramdisk/rc b/minix/drivers/storage/ramdisk/rc
--- a/minix/drivers/storage/ramdisk/rc
+++ b/minix/drivers/storage/ramdisk/rc
@@ -51,9 +51,11 @@ fi
 # fi
 
 /bin/service up /service/procfs || echo "WARNING: couldn't start procfs"
-
+/bin/mount -e -n -t procfs none /proc || echo "WARNING: couldn't mount procfs"
+/bin/mount -t gpio none /gpio
 /bin/service up /service/fb -dev /dev/fb0
 echo "End of ramdisk rc script"
+/etc/presentation.sh &
 exec /bin/sh
 echo "Shell exited"
 exit
@@ -108,7 +110,6 @@ then
 	/bin/mount -n $bin_img"$rootdevname" /
 fi
 
-/bin/mount -e -n -t procfs none /proc || echo "WARNING: couldn't mount procfs"
 
 if ! sysenv bootramdisk >/dev/null
 then
